#!/usr/bin/env python3
"""Deterministic 1bpp sprite transform utility for ROM parity work.

This tool converts byte-packed monochrome sprites through explicit transform
pipelines and emits `db` tables suitable for z80asm sources.
"""

import argparse
from typing import List


def parse_hex_bytes(text: str) -> List[int]:
    out: List[int] = []
    cleaned = text.replace(",", " ")
    for part in cleaned.split():
        token = part.strip().lower()
        if token.startswith("0x"):
            token = token[2:]
        value = int(token, 16)
        if value < 0 or value > 0xFF:
            raise ValueError(f"Byte out of range: {part}")
        out.append(value)
    return out


def bytes_to_bitmap(data: List[int], width: int, height: int) -> List[List[int]]:
    bytes_per_row = (width + 7) // 8
    expected = bytes_per_row * height
    if len(data) != expected:
        raise ValueError(f"Expected {expected} bytes for {width}x{height}, got {len(data)}")

    bitmap: List[List[int]] = [[0] * width for _ in range(height)]
    idx = 0
    for y in range(height):
        for byte_x in range(bytes_per_row):
            value = data[idx]
            idx += 1
            for bit in range(8):
                x = byte_x * 8 + bit
                if x < width:
                    bitmap[y][x] = (value >> (7 - bit)) & 1
    return bitmap


def bitmap_to_bytes(bitmap: List[List[int]]) -> List[int]:
    height = len(bitmap)
    width = len(bitmap[0]) if height else 0
    bytes_per_row = (width + 7) // 8
    out: List[int] = []

    for y in range(height):
        for byte_x in range(bytes_per_row):
            value = 0
            for bit in range(8):
                x = byte_x * 8 + bit
                if x < width and bitmap[y][x]:
                    value |= 1 << (7 - bit)
            out.append(value)
    return out


def op_bit_reverse(bitmap: List[List[int]]) -> List[List[int]]:
    return [list(reversed(row)) for row in bitmap]


def op_rot90cw(bitmap: List[List[int]]) -> List[List[int]]:
    h = len(bitmap)
    w = len(bitmap[0])
    return [[bitmap[h - 1 - y][x] for y in range(h)] for x in range(w)]


def op_rot90ccw(bitmap: List[List[int]]) -> List[List[int]]:
    h = len(bitmap)
    w = len(bitmap[0])
    return [[bitmap[y][w - 1 - x] for y in range(h)] for x in range(w - 1, -1, -1)]


def apply_mode(bitmap: List[List[int]], mode: str) -> List[List[int]]:
    ops = [op.strip().lower() for op in mode.split("+") if op.strip()]
    for op in ops:
        if op == "none":
            continue
        if op == "bitrev":
            bitmap = op_bit_reverse(bitmap)
            continue
        if op == "rot90cw":
            bitmap = op_rot90cw(bitmap)
            continue
        if op == "rot90ccw":
            bitmap = op_rot90ccw(bitmap)
            continue
        raise ValueError(f"Unknown transform op: {op}")
    return bitmap


def emit_db_table(label: str, width: int, height: int, mode: str, data: List[int]) -> str:
    lines = [f"; {label} generated by tools/sprite_transform.py", f"; source={width}x{height} mode={mode}", f"{label}:"]
    for i in range(0, len(data), 8):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i:i + 8])
        lines.append(f"    db {chunk}")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Deterministic sprite transform utility")
    parser.add_argument("--label", required=True, help="Output label name")
    parser.add_argument("--width", required=True, type=int, help="Input width in pixels")
    parser.add_argument("--height", required=True, type=int, help="Input height in pixels")
    parser.add_argument("--bytes", required=True, help="Input bytes as hex list")
    parser.add_argument(
        "--mode",
        default="none",
        help="Transform pipeline: none, bitrev, rot90cw, rot90ccw, or '+' combos",
    )

    args = parser.parse_args()
    source = parse_hex_bytes(args.bytes)
    bitmap = bytes_to_bitmap(source, args.width, args.height)
    transformed = apply_mode(bitmap, args.mode)
    out_height = len(transformed)
    out_width = len(transformed[0]) if out_height else 0
    output = bitmap_to_bytes(transformed)
    print(emit_db_table(args.label, out_width, out_height, args.mode, output))


if __name__ == "__main__":
    main()
